[dev]
framework = "#static"

[build]
command = "echo No build for this site, we are living on the edge"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[[edge_functions]] 
path = "/*" 
function = "hello"
